# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-04 19:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exterior',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Vigilancia', models.CharField(max_length=50)),
                ('Parqueadero', models.CharField(max_length=50)),
                ('Salon_social', models.CharField(max_length=50)),
                ('Numero_pisos', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='inmueble',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=35)),
                ('subtipo', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='interior',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cuartos', models.CharField(max_length=50)),
                ('Banios', models.CharField(max_length=50)),
                ('Closets', models.CharField(max_length=50)),
                ('Calentador', models.CharField(max_length=50)),
            ],
        ),
    ]
