# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-04 20:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prueba', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='General',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=35)),
                ('subtipo', models.CharField(max_length=35)),
                ('Direccion', models.CharField(max_length=35)),
                ('Ciudad', models.CharField(max_length=35)),
                ('Departamento', models.CharField(max_length=35)),
                ('Pais', models.CharField(max_length=35)),
                ('Telefono', models.CharField(max_length=35)),
            ],
        ),
        migrations.DeleteModel(
            name='inmueble',
        ),
    ]
