# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-05 22:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prueba', '0002_auto_20190104_1537'),
    ]

    operations = [
        migrations.RenameField(
            model_name='general',
            old_name='subtipo',
            new_name='Subtipo',
        ),
        migrations.RenameField(
            model_name='general',
            old_name='tipo',
            new_name='Tipo',
        ),
        migrations.AlterField(
            model_name='exterior',
            name='Numero_pisos',
            field=models.IntegerField(max_length=50),
        ),
        migrations.AlterField(
            model_name='exterior',
            name='Salon_social',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='interior',
            name='Banios',
            field=models.IntegerField(max_length=50),
        ),
        migrations.AlterField(
            model_name='interior',
            name='Calentador',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='interior',
            name='Closets',
            field=models.IntegerField(max_length=50),
        ),
        migrations.AlterField(
            model_name='interior',
            name='Cuartos',
            field=models.FloatField(max_length=50),
        ),
    ]
